Commenting this out avoids failures in our app's suite for 1.9.2-p180, and doesn't cause any failures in RR specs.
This is from Nathan Sobo and Glenn Jahnke
Here is the stack trace. We can't manage to produce a failing test case in RR's suite after an hour of trying.

NotImplementedError: super from singleton method that is defined to multiple classes is not supported; this will be fixed in 1.9.3 or later
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rr-1.0.2/lib/rr/injections/singleton_method_added_injection.rb:33:in `singleton_method_added'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rr-1.0.2/lib/rr/injections/singleton_method_added_injection.rb:46:in `block in bind'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rr-1.0.2/lib/rr/injections/method_missing_injection.rb:46:in `alias_method'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rr-1.0.2/lib/rr/injections/method_missing_injection.rb:46:in `block in reset'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rr-1.0.2/lib/rr/injections/method_missing_injection.rb:43:in `class_eval'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rr-1.0.2/lib/rr/injections/method_missing_injection.rb:43:in `reset'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rr-1.0.2/lib/rr/space.rb:96:in `block in reset_method_missing_injections'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rr-1.0.2/lib/rr/hash_with_object_id_key.rb:29:in `block in each'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rr-1.0.2/lib/rr/hash_with_object_id_key.rb:28:in `each'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rr-1.0.2/lib/rr/hash_with_object_id_key.rb:28:in `each'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rr-1.0.2/lib/rr/space.rb:95:in `reset_method_missing_injections'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rr-1.0.2/lib/rr/space.rb:63:in `reset'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/mocking/with_rr.rb:20:in `teardown_mocks_for_rspec'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example.rb:151:in `run_after_each'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example.rb:53:in `block (2 levels) in run'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example.rb:106:in `with_around_hooks'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example.rb:46:in `block in run'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example.rb:99:in `block in with_pending_capture'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example.rb:98:in `catch'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example.rb:98:in `with_pending_capture'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example.rb:45:in `run'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example_group.rb:262:in `block in run_examples'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example_group.rb:258:in `map'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example_group.rb:258:in `run_examples'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example_group.rb:232:in `run'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example_group.rb:233:in `block in run'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example_group.rb:233:in `map'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example_group.rb:233:in `run'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example_group.rb:233:in `block in run'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example_group.rb:233:in `map'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/example_group.rb:233:in `run'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/command_line.rb:27:in `block (2 levels) in run'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/command_line.rb:27:in `map'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/command_line.rb:27:in `block in run'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/reporter.rb:12:in `report'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/command_line.rb:24:in `run'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/runner.rb:55:in `run_in_process'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/runner.rb:44:in `run'
/Users/pivotal/.rvm/gems/ruby-1.9.2-p180@mailbypass/gems/rspec-core-2.5.1/lib/rspec/core/runner.rb:10:in `block in autorun'